# Generated by Django 4.1.7 on 2023-04-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate", old_name="exp", new_name="experience",
        ),
        migrations.AddField(
            model_name="candidate",
            name="skills",
            field=models.CharField(max_length=225, null=True, verbose_name="Skills"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("SELECTED", "selected"),
                    ("REJECTED", "rejected"),
                    ("SCREENING", "screening"),
                    ("TELEPHONE", "telephone"),
                    ("CODING", "coding"),
                    ("F2F", "f2f"),
                    ("MAKEOFFER", "makeoffer"),
                ],
                default="SELECTED",
                max_length=20,
            ),
        ),
    ]
