# Generated by Django 4.1.7 on 2023-04-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateapplicationform",
            name="current_location",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Linkedin", "Linkedin"),
                    ("Dribble", "Dribble"),
                    ("Self", "Self"),
                    ("Angellist", "Angellist"),
                    ("Career Page", "Career Page"),
                ],
                default="Linkedin",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="feedbacknotes",
            name="communication_rating",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="feedbacknotes",
            name="event_time_feedback",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="feedbacknotes",
            name="logicalskills_rating",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="feedbacknotes",
            name="techinicalskills_rating",
            field=models.CharField(max_length=10),
        ),
    ]
