# Generated by Django 4.1.7 on 2023-04-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_candidateapplicationform_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('SELECTED', 'selected'), ('REJECTED', 'rejected'), ('SCREENING', 'screening'), ('TELEPHONE', 'telephone'), ('CODING', 'coding'), ('F2F', 'f2f'), ('MAKEOFFER', 'makeoffer')], default='screening', max_length=20),
        ),
    ]
