# Generated by Django 4.1.7 on 2023-04-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_candidate_source"),
    ]

    operations = [
        migrations.RemoveField(model_name="candidate", name="stage",),
        migrations.RemoveField(model_name="jobapplication", name="feedback_note",),
        migrations.RemoveField(model_name="jobapplication", name="user_note",),
        migrations.AlterField(
            model_name="candidate",
            name="designation",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Designation"
            ),
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_note", models.CharField(max_length=250)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.jobapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_feedback", models.CharField(max_length=250)),
                ("communication_rating", models.IntegerField(max_length=10)),
                ("logicalskills_rating", models.IntegerField(max_length=10)),
                ("techinicalskills_rating", models.IntegerField(max_length=10)),
                (
                    "application_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.jobapplication",
                    ),
                ),
                (
                    "given_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
