# Generated by Django 4.1.7 on 2023-04-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_candidate_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="archived",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(upload_to="uploads/", verbose_name="Resume/CV "),
        ),
    ]
